[trojan]
enabled = true
server_addr = "[::]:443"
cert_path = "server.crt"
key_path = "server.key"
fallback_addr = "127.0.0.1:80"

[[trojan.users]]
uuid = "e3f1c2b4a5d6478e9f0b1c2d3e4f5a6b"
password = "password1"

[[trojan.users]]
uuid = "e3f1c2b4a5d6478e9f0b1c2d3e4f5a88"
password = "password2"

[tuic]

enabled = false
server_addr = "[::]:443"
cert_path = "server.crt"
key_path = "server.key"

[[tuic.users]]
uuid = "e3f1c2b4a5d6478e9f0b1c2d3e4f5a6b"
password = "password1"

[[tuic.users]]
uuid = "e3f1c2b4a5d6478e9f0b1c2d3e4f5a88"
password = "password2"

[dns_cache]
max_entries = 2000
ttl_secs = 300

[udp_session]
session_timeout = 30
socket_timeout = 10

